libxml2: revert from 2.13.3 to 2.12.8 because of C99 compatibility issues (#59)
Build fails on macOS using Xcode:

/Users/clamav_jenkins_svc/.mussels/cache/work/host-static/libxml2-v2.13.3/dict.c:970:17:
error: implicit declaration of function 'getentropy' is invalid in C99
[-Werror,-Wimplicit-function-declaration]

It looks like all known CVEs are fixed in 2.12.8.
Homebrew is still on 2.12.8 as well.